export const SET_REFERENCE_FREQUENCY = 'SET_REFERENCE_FREQUENCY';
export const SET_LOW_OCTAVE = 'SET_LOW_OCTAVE';
export const SET_HIGH_OCTAVE = 'SET_HIGH_OCTAVE';
export const RESET_SETTINGS_TO_DEFAULT = 'RESET_SETTINGS_TO_DEFAULT';
export const SET_CURRENT_BPM = 'SET_CURRENT_BPM';
export const SET_HZ_PRECISION = 'SET_HZ_PRECISION';
export const SET_MS_PRECISION = 'SET_MS_PRECISION';
